# Generated by Django 3.2.13 on 2022-05-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20220530_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='candidate',
        ),
        migrations.AddField(
            model_name='skill',
            name='candidate',
            field=models.ManyToManyField(to='matcher.Candidate'),
        ),
    ]
