# Generated by Django 4.0.4 on 2022-06-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0010_alter_candidate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='name_match',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skill_matches',
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_matches', models.IntegerField(default=0)),
                ('name_match', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='matcher.candidate')),
            ],
        ),
    ]
